#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."
unset PAPERCLIP_AGENT_ID PAPERCLIP_API_KEY PAPERCLIP_API_URL PAPERCLIP_COMPANY_ID PAPERCLIP_RUN_ID PAPERCLIP_TASK_ID PAPERCLIP_WAKE_COMMENT_ID PAPERCLIP_WAKE_PAYLOAD_JSON PAPERCLIP_WAKE_REASON PAPERCLIP_PROJECT_ID PAPERCLIP_GOAL_ID PAPERCLIP_PARENT_ISSUE_ID
export SHOWCASE_PAPERCLIP_RUN_ID="showcase-telegram-runtime"
node showcase/server.js
